run_desc = "REMOVEME QUICK TEST debug conditional"

root_data_dir = "/projects/imagesets/BBBC021/BBBC021_comp_conc_nice_phen"
# selected_datasets = ["DMSO", "cytochalasin B_0.01", "cytochalasin B_0.03", "cytochalasin B_0.1", "cytochalasin B_0.3", "cytochalasin B_1.0", "cytochalasin B_10.0", "cytochalasin B_3.0", "cytochalasin B_30.0"]
selected_datasets = ["DMSO", "cytochalasin B_30.0"]

image_size = 32
batch_size = 1280
num_train_timesteps = 1000 
num_inference_steps = 50 
beta_start = 0.0001 
beta_end = 0.02 
beta_schedule = "linear" 

nb_epochs = 500
save_every = 50
generate_every = 1
nb_generated_images = 100 # Authors recommend at least 10,000(!)

compile = "False"

Inception_feat_dim = 64
# Possible values:
# - 64: first max pooling features
# - 192: second max pooling features
# - 768: pre-aux classifier features
# - 2048: final average pooling features (this is the default)
# Per the Authors of the original TF implementation (https://github.com/bioinf-jku/TTUR):
#   "The number of samples to calculate the Gaussian statistics (mean and covariance) 
#   should be greater than the dimension of the coding layer"
FID_recompute = "False"

class_emb_size = 2

# Note: boolean must be given in string format!
