run_desc = "A short description of the run *added to the file name*"

root_data_dir = "/root/folder/of/datasets"
selected_datasets = ["cats", "dogs", "horses", "humans"]

image_size = 256
batch_size = 64
num_train_timesteps = 1000 
num_inference_steps = 50 
beta_start = 0.0001 
beta_end = 0.02 
beta_schedule = "linear" 

nb_epochs = 500
save_every = 50
generate_every = 20
nb_generated_images = 1000 # FID authors recommend at least 10,000(!)

compile = "False" # booleans must be given in string format!

class_emb_dim = 4
